### ISSUE TITLE
Can not download Tick data from TianRuan source.

### ISSUE THREAD

**Issue by LJingnan** [vnpy/vnpy_tinysoft#2]
using datamanager to download data and return this error

![261f563faa9000e478da449bd2d4953](https://user-images.githubusercontent.com/43166853/139389630-1e428671-b357-4735-9dff-2e97dcf8e4cd.png)

**Comment by LJingnan** [comment]
> 可参考https://github.com/vnpy/vnpy_tinysoft/pull/3/files 试试看
not work

**Comment by LJingnan** [comment]
> 可参考https://github.com/vnpy/vnpy_tinysoft/pull/3/files 试试看

another error

![image](https://user-images.githubusercontent.com/43166853/139534288-65e82780-f475-4c18-934b-e2493e61faf1.png)

**Comment by noranhe** [comment]
请参考新的修改https://github.com/vnpy/vnpy_tinysoft/pull/3/files 试试看

**Comment by noranhe** [comment]
请参考新的修改https://github.com/vnpy/vnpy_tinysoft/pull/3/files 试试看

**Comment by vnpy** [comment]
已修复
